// <auto-generated />
using System;
using ChallangeMottu.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ChallangeMottu.Infrastructure.Migrations
{
    [DbContext(typeof(ChallangeMottuContext))]
    partial class ChallangeMottuContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChallangeMottu.Domain.LocalizacaoAtual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<double>("CoordenadaX")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("CoordenadaY")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime>("DataHoraAtualizacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("MotoId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("MotoId");

                    b.ToTable("T_LOCALIZACAO_ATUAL-MOTTU", (string)null);
                });

            modelBuilder.Entity("ChallangeMottu.Domain.Moto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("SYS_GUID()");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("PLACA");

                    b.Property<string>("Posicao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("STATUS");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ULTIMA_ATUALIZACAO");

                    b.HasKey("Id");

                    b.ToTable("T_MOTOS-MOTTU", (string)null);
                });

            modelBuilder.Entity("ChallangeMottu.Domain.LocalizacaoAtual", b =>
                {
                    b.HasOne("ChallangeMottu.Domain.Moto", "Moto")
                        .WithMany()
                        .HasForeignKey("MotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moto");
                });
#pragma warning restore 612, 618
        }
    }
}
